apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: 520491554233.dkr.ecr.us-west-2.amazonaws.com/capstone:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          protocol: TCP
